# Canvas settings.
canvas:
  prefix: "https://csbsju.instructure.com"
  course: "13537"
  start-date: "2020-01-13"
  # Exclude the following files/folders from uploading. Canvas Workflow gives
  # precedence to include over exclude, so you can selectively include
  # files/folders that exist in excluded directories.
  exclude:
    - files/slides
  # Selectively include files/folders that have been previously excluded.
  include:
    - files/slides/**/*-final.pdf

# Exclude the following files/folders from processing. Jekyll currently gives
# exclude precedence over include, so list files/folders to be excluded here.
exclude:
  - AUTHORS
  - LICENSE
  - files
  - Gemfile*
  - vendor
